# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstore.proto\x12\x05store\x1a\x1bgoogle/protobuf/empty.proto\"\x16\n\x05Price\x12\r\n\x05value\x18\x01 \x01(\x05\"#\n\x0fPurchaseRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\"\"\n\x10PurchaseResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"O\n\x15StoreShutdownResponse\x12\x16\n\x0eseller_balance\x18\x01 \x01(\x05\x12\x1e\n\x16wallet_shutdown_status\x18\x02 \x01(\x05\x32\xb8\x01\n\x05Store\x12\x30\n\x08GetPrice\x12\x16.google.protobuf.Empty\x1a\x0c.store.Price\x12;\n\x08Purchase\x12\x16.store.PurchaseRequest\x1a\x17.store.PurchaseResponse\x12@\n\x08Shutdown\x12\x16.google.protobuf.Empty\x1a\x1c.store.StoreShutdownResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'store_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRICE']._serialized_start=51
  _globals['_PRICE']._serialized_end=73
  _globals['_PURCHASEREQUEST']._serialized_start=75
  _globals['_PURCHASEREQUEST']._serialized_end=110
  _globals['_PURCHASERESPONSE']._serialized_start=112
  _globals['_PURCHASERESPONSE']._serialized_end=146
  _globals['_STORESHUTDOWNRESPONSE']._serialized_start=148
  _globals['_STORESHUTDOWNRESPONSE']._serialized_end=227
  _globals['_STORE']._serialized_start=230
  _globals['_STORE']._serialized_end=414
# @@protoc_insertion_point(module_scope)
