# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wallet.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cwallet.proto\x12\x06wallet\x1a\x1bgoogle/protobuf/empty.proto\"\x16\n\x08WalletId\x12\n\n\x02id\x18\x01 \x01(\t\"\x18\n\x07\x42\x61lance\x12\r\n\x05value\x18\x01 \x01(\x05\"1\n\x13PaymentOrderRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"8\n\x14PaymentOrderResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x10\n\x08order_id\x18\x02 \x01(\x05\"W\n\x0fTransferRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x1a\n\x12\x63onfirmation_value\x18\x02 \x01(\x05\x12\x16\n\x0e\x64\x65stination_id\x18\x03 \x01(\t\"\"\n\x10TransferResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"O\n\x10ShutdownResponse\x12\x16\n\x0epending_orders\x18\x01 \x01(\x05\x12#\n\x07wallets\x18\x02 \x03(\x0b\x32\x12.wallet.WalletData\"\'\n\nWalletData\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\x32\x80\x02\n\x06Wallet\x12/\n\nGetBalance\x12\x10.wallet.WalletId\x1a\x0f.wallet.Balance\x12H\n\x0b\x43reateOrder\x12\x1b.wallet.PaymentOrderRequest\x1a\x1c.wallet.PaymentOrderResponse\x12=\n\x08Transfer\x12\x17.wallet.TransferRequest\x1a\x18.wallet.TransferResponse\x12<\n\x08Shutdown\x12\x16.google.protobuf.Empty\x1a\x18.wallet.ShutdownResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wallet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WALLETID']._serialized_start=53
  _globals['_WALLETID']._serialized_end=75
  _globals['_BALANCE']._serialized_start=77
  _globals['_BALANCE']._serialized_end=101
  _globals['_PAYMENTORDERREQUEST']._serialized_start=103
  _globals['_PAYMENTORDERREQUEST']._serialized_end=152
  _globals['_PAYMENTORDERRESPONSE']._serialized_start=154
  _globals['_PAYMENTORDERRESPONSE']._serialized_end=210
  _globals['_TRANSFERREQUEST']._serialized_start=212
  _globals['_TRANSFERREQUEST']._serialized_end=299
  _globals['_TRANSFERRESPONSE']._serialized_start=301
  _globals['_TRANSFERRESPONSE']._serialized_end=335
  _globals['_SHUTDOWNRESPONSE']._serialized_start=337
  _globals['_SHUTDOWNRESPONSE']._serialized_end=416
  _globals['_WALLETDATA']._serialized_start=418
  _globals['_WALLETDATA']._serialized_end=457
  _globals['_WALLET']._serialized_start=460
  _globals['_WALLET']._serialized_end=716
# @@protoc_insertion_point(module_scope)
